/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/3N4gvec1cbe
 */
import Link from "next/link"
import { Button } from "@/components/ui/button"
import { CardTitle, CardDescription, CardHeader, CardContent, CardFooter, Card } from "@/components/ui/card"
import { Label } from "@/components/ui/label"
import { Input } from "@/components/ui/input"
import { Textarea } from "@/components/ui/textarea"
import { SVGProps } from "react"
type Props = SVGProps<SVGSVGElement>;

export function Second() {
  return (
    <div className="grid items-start gap-4 lg:grid-cols-[300px_1fr]">
      <div className="flex flex-col gap-2">
        <div className="flex items-center gap-4">
          <Link className="flex items-center gap-2 font-semibold" href="#">
            <SquareIcon className="h-6 w-6" />
            <span className="">MintIt</span>
          </Link>
          <Button className="ml-auto lg:hidden" size="sm" variant="outline">
            Connect wallet
          </Button>
        </div>
        <div className="flex items-center gap-4">
          <div className="flex items-center gap-2">
            <img
              alt="Avatar"
              className="rounded-full"
              height="64"
              src="/placeholder.svg"
              style={{
                aspectRatio: "64/64",
                objectFit: "cover",
              }}
              width="64"
            />
            <div className="flex flex-col">
              <h2 className="text-2xl font-bold">Alice</h2>
              <p className="text-sm text-gray-500 dark:text-gray-400">Wallet address</p>
              <p className="font-medium text-sm">0x8FcAa9b3D1a24d1A5B2F4bC7Ca3B66B5eD3Ae6f8</p>
            </div>
          </div>
          <Button className="ml-auto" size="sm">
            Connect another wallet
          </Button>
        </div>
        <div className="grid gap-4">
          <Card>
            <CardHeader>
              <CardTitle>Mint NFT</CardTitle>
              <CardDescription>Upload your digital asset and fill in the details to create your NFT</CardDescription>
            </CardHeader>
            <CardContent>
              <div className="flex flex-col gap-4">
                <div className="border border-dashed border-gray-200 rounded-lg w-full h-[200px] flex items-center justify-center text-gray-500 dark:border-gray-800 dark:text-gray-400">
                  <ImageIcon className="h-6 w-6" />
                  <span className="sr-only">Upload your file</span>
                </div>
                <div className="grid gap-2">
                  <Label className="text-sm" htmlFor="file">
                    Upload your file
                  </Label>
                  <Input accept=".jpg, .png, .mp4" id="file" type="file" />
                </div>
              </div>
            </CardContent>
            <CardFooter>
              <Button className="ml-auto">Next</Button>
            </CardFooter>
          </Card>
          <Card>
            <CardHeader>
              <CardTitle>Set Metadata</CardTitle>
              <CardDescription>Fill in the details for your NFT</CardDescription>
            </CardHeader>
            <CardContent>
              <div className="grid gap-4">
                <div className="grid gap-1">
                  <Label className="text-sm" htmlFor="name">
                    Name
                  </Label>
                  <Input id="name" placeholder="Enter the name of your NFT" />
                </div>
                <div className="grid gap-1">
                  <Label className="text-sm" htmlFor="description">
                    Description
                  </Label>
                  <Textarea
                    className="min-h-[100px]"
                    id="description"
                    placeholder="Enter the description of your NFT"
                  />
                </div>
              </div>
            </CardContent>
            <CardFooter>
              <Button variant="outline">Back</Button>
              <Button className="ml-auto">Create NFT</Button>
            </CardFooter>
          </Card>
        </div>
      </div>
      <div className="grid gap-4">
        <Card>
          <CardHeader>
            <CardTitle>Connect Wallet</CardTitle>
            <CardDescription>Connect your wallet to get started</CardDescription>
          </CardHeader>
          <CardContent>
            <div className="flex flex-col gap-2">
              <Button className="justify-start">
                <WalletIcon className="w-4 h-4 mr-2.5 inline-block" />
                Metamask
              </Button>
              <Button className="justify-start">
                <GhostIcon className="w-4 h-4 mr-2.5 inline-block" />
                Phantom
              </Button>
              <Button className="justify-start">
                <SaladIcon className="w-4 h-4 mr-2.5 inline-block" />
                Sollet
              </Button>
              <Button className="justify-start">
                <BlocksIcon className="w-4 h-4 mr-2.5 inline-block" />
                Blocto
              </Button>
            </div>
          </CardContent>
        </Card>
        <Card>
          <CardHeader>
            <CardTitle>Supported Blockchains</CardTitle>
            <CardDescription>Learn more about the blockchains we support</CardDescription>
          </CardHeader>
          <CardContent>
            <div className="grid gap-4">
              <div className="flex items-center gap-4">
                <BitcoinIcon className="w-8 h-8" />
                <div className="flex flex-col">
                  <h3 className="font-semibold">Ethereum</h3>
                  <p className="text-sm text-gray-500 dark:text-gray-400">
                    The world's most popular blockchain. Gas fees are paid in ETH.
                  </p>
                </div>
                <Button className="ml-auto" size="sm">
                  Select
                </Button>
              </div>
              <div className="flex items-center gap-4">
                <SunIcon className="w-8 h-8" />
                <div className="flex flex-col">
                  <h3 className="font-semibold">Solana</h3>
                  <p className="text-sm text-gray-500 dark:text-gray-400">
                    Fast and low-cost transactions. Gas fees are paid in SOL.
                  </p>
                </div>
                <Button className="ml-auto" size="sm">
                  Select
                </Button>
              </div>
              <div className="flex items-center gap-4">
                <WorkflowIcon className="w-8 h-8" />
                <div className="flex flex-col">
                  <h3 className="font-semibold">Flow</h3>
                  <p className="text-sm text-gray-500 dark:text-gray-400">
                    Built by Dapper Labs, home of NBA Top Shot. Gas fees are paid in FLOW.
                  </p>
                </div>
                <Button className="ml-auto" size="sm">
                  Select
                </Button>
              </div>
              <div className="flex items-center gap-4">
                <MountainSnowIcon className="w-8 h-8" />
                <div className="flex flex-col">
                  <h3 className="font-semibold">Avalanche</h3>
                  <p className="text-sm text-gray-500 dark:text-gray-400">
                    High-performance blockchain for decentralized applications. Gas fees are paid in AVAX.
                  </p>
                </div>
                <Button className="ml-auto" size="sm">
                  Select
                </Button>
              </div>
            </div>
          </CardContent>
        </Card>
      </div>
    </div>
  )
}


function SquareIcon(props : Props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <rect width="18" height="18" x="3" y="3" rx="2" />
    </svg>
  )
}


function ImageIcon(props: Props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <rect width="18" height="18" x="3" y="3" rx="2" ry="2" />
      <circle cx="9" cy="9" r="2" />
      <path d="m21 15-3.086-3.086a2 2 0 0 0-2.828 0L6 21" />
    </svg>
  )
}


function WalletIcon(props : Props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M21 12V7H5a2 2 0 0 1 0-4h14v4" />
      <path d="M3 5v14a2 2 0 0 0 2 2h16v-5" />
      <path d="M18 12a2 2 0 0 0 0 4h4v-4Z" />
    </svg>
  )
}


function GhostIcon(props : Props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M9 10h.01" />
      <path d="M15 10h.01" />
      <path d="M12 2a8 8 0 0 0-8 8v12l3-3 2.5 2.5L12 19l2.5 2.5L17 19l3 3V10a8 8 0 0 0-8-8z" />
    </svg>
  )
}


function SaladIcon(props : Props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M7 21h10" />
      <path d="M12 21a9 9 0 0 0 9-9H3a9 9 0 0 0 9 9Z" />
      <path d="M11.38 12a2.4 2.4 0 0 1-.4-4.77 2.4 2.4 0 0 1 3.2-2.77 2.4 2.4 0 0 1 3.47-.63 2.4 2.4 0 0 1 3.37 3.37 2.4 2.4 0 0 1-1.1 3.7 2.51 2.51 0 0 1 .03 1.1" />
      <path d="m13 12 4-4" />
      <path d="M10.9 7.25A3.99 3.99 0 0 0 4 10c0 .73.2 1.41.54 2" />
    </svg>
  )
}


function BlocksIcon(props : Props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <rect width="7" height="7" x="14" y="3" rx="1" />
      <path d="M10 21V8a1 1 0 0 0-1-1H4a1 1 0 0 0-1 1v12a1 1 0 0 0 1 1h12a1 1 0 0 0 1-1v-5a1 1 0 0 0-1-1H3" />
    </svg>
  )
}


function BitcoinIcon(props : Props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M11.767 19.089c4.924.868 6.14-6.025 1.216-6.894m-1.216 6.894L5.86 18.047m5.908 1.042-.347 1.97m1.563-8.864c4.924.869 6.14-6.025 1.215-6.893m-1.215 6.893-3.94-.694m5.155-6.2L8.29 4.26m5.908 1.042.348-1.97M7.48 20.364l3.126-17.727" />
    </svg>
  )
}


function SunIcon(props : Props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="12" cy="12" r="4" />
      <path d="M12 2v2" />
      <path d="M12 20v2" />
      <path d="m4.93 4.93 1.41 1.41" />
      <path d="m17.66 17.66 1.41 1.41" />
      <path d="M2 12h2" />
      <path d="M20 12h2" />
      <path d="m6.34 17.66-1.41 1.41" />
      <path d="m19.07 4.93-1.41 1.41" />
    </svg>
  )
}


function WorkflowIcon(props : Props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <rect width="8" height="8" x="3" y="3" rx="2" />
      <path d="M7 11v4a2 2 0 0 0 2 2h4" />
      <rect width="8" height="8" x="13" y="13" rx="2" />
    </svg>
  )
}


function MountainSnowIcon(props : Props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m8 3 4 8 5-5 5 15H2L8 3z" />
      <path d="M4.14 15.08c2.62-1.57 5.24-1.43 7.86.42 2.74 1.94 5.49 2 8.23.19" />
    </svg>
  )
}
