/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/vNg2PV5NgXS
 */
import { Label } from "@/components/ui/label"
import { Input } from "@/components/ui/input"
import { Textarea } from "@/components/ui/textarea"
import { Button } from "@/components/ui/button"

export function Third() {
  return (
    <div className="w-full space-y-12">
      <div className="space-y-4">
        <div className="space-y-2">
          <h1 className="text-3xl font-bold">Mint your NFT</h1>
          <p className="text-gray-500 dark:text-gray-400">
            Fill out the form to mint your NFT. You can connect your wallet and select the blockchain you want to mint
            on.
          </p>
        </div>
        <div className="grid gap-4">
          <div className="grid gap-1.5">
            <Label htmlFor="title">Title</Label>
            <Input id="title" placeholder="Enter the title of your NFT" />
          </div>
          <div className="grid gap-1.5">
            <Label htmlFor="description">Description</Label>
            <Textarea className="min-h-[100px]" id="description" placeholder="Enter the description of your NFT" />
          </div>
          <div className="grid gap-1.5">
            <Label>Image</Label>
            <Input id="file" type="file" />
          </div>
          <div className="grid gap-1.5">
            <Label htmlFor="attributes">Attributes</Label>
            <Textarea
              className="min-h-[100px]"
              id="attributes"
              placeholder="Enter the attributes of your NFT (e.g., color: blue, size: medium)"
            />
          </div>
          <Button>Connect Wallet</Button>
        </div>
      </div>
      <div className="space-y-4">
        <div className="space-y-2">
          <h2 className="text-2xl font-bold">Your NFT</h2>
          <p className="text-gray-500 dark:text-gray-400">
            Your NFT will be minted on the Ethereum blockchain. The unique token ID will be displayed after you submit
            the form.
          </p>
        </div>
        <div className="grid gap-4">
          <div className="grid gap-1.5">
            <Label htmlFor="title">Title</Label>
            <Input id="title" placeholder="Enter the title of your NFT" />
          </div>
          <div className="grid gap-1.5">
            <Label htmlFor="description">Description</Label>
            <Textarea className="min-h-[100px]" id="description" placeholder="Enter the description of your NFT" />
          </div>
          <div className="grid gap-1.5">
            <Label>Image</Label>
            <Input id="file" type="file" />
          </div>
          <div className="grid gap-1.5">
            <Label htmlFor="attributes">Attributes</Label>
            <Textarea
              className="min-h-[100px]"
              id="attributes"
              placeholder="Enter the attributes of your NFT (e.g., color: blue, size: medium)"
            />
          </div>
          <Button>Submit</Button>
        </div>
      </div>
    </div>
  )
}
